### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by limelect** [HemulGM/DelphiOpenAI#14]
Just uses OpenAI;  Nothing else !!!!
Compile with 10.2.3

On unit OpenAI.Completions;
error at        end);

[dcc32 Error] OpenAI.Completions.pas(218): E2250 There is no overloaded version of 'TOpenAIAPI.Post<OpenAI.Completions.TCompletionParams>' that can be called with these arguments

P.S i have a few versions from you. What is going on?

**Comment by HemulGM** [comment]
I have no way to check compilation on versions below 10.3

**Comment by yeohray** [comment]
I have the same issue with Delphi 10.3, specifically 26.0.34749.6593.  Should I be using a newer version?  Thank you.

**Comment by HemulGM** [comment]
Haven't checked for 10.3 for a long time. For a completely correct operation, I recommend using D11+

**Comment by limelect** [comment]
And spend just a lot of dollars to test a program?

**Comment by HemulGM** [comment]
> And spend just a lot of dollars to test a program?

You can take the release. I just picked a fresh one today
